import assert from "node:assert/strict";
import { acceptFixtureInvitation } from "./check-account-delivery.js";
import mongoose from "mongoose";
import request from "supertest";
import { nanoid } from "nanoid";
import { app } from "../app.js";
import { User } from "../models/User.js";
import { Gym } from "../models/Gym.js";
import { RoleAssignment } from "../models/Auth.js";
import { MemberProfile } from "../models/Member.js";
import { MembershipPlan, Payment, Subscription, SubscriptionEvent } from "../models/Commerce.js";
import { AttendanceEvent } from "../models/Attendance.js";
import { Notification } from "../models/Engagement.js";
import { OWNER_DEFAULT_PERMISSIONS } from "../constants/domain.js";
import { createSession } from "../services/tokenService.js";
import { globalStreak } from "../services/socialService.js";

// Only invoked inside the parent runner's owned temporary database. No provider
// calls, database connections, cleanup operations, or migrations are performed.
export async function checkMembershipStreakEnhancements({ assertDatabase }: { assertDatabase: () => void }) {
  assertDatabase();
  assert.match(mongoose.connection.db!.databaseName, /^gfv_[a-f0-9]{32}$/);
  const results: string[] = [];
  const makeUser = (name: string, role = "USER", timezone = "UTC") => User.create({ publicId: nanoid(), name, email: `${nanoid()}@verification.invalid`, roles: [role], activeRole: role, status: "ACTIVE", social: { timezone } });
  const owner = await makeUser("Lifecycle owner", "GYM_OWNER"), otherOwner = await makeUser("Other lifecycle owner", "GYM_OWNER");
  const user = await makeUser("Lifecycle member"), directUser = await makeUser("Direct member");
  const makeGym = (ownerId: unknown) => Gym.create({ publicId: nanoid(), ownerId, name: "Lifecycle verification gym", slug: nanoid().toLowerCase(), location: { type: "Point", coordinates: [77, 12] }, timezone: "UTC", status: "ACTIVE", verificationStatus: "VERIFIED", platformSubscriptionStatus: "ACTIVE" });
  const gym = await makeGym(owner._id), otherGym = await makeGym(otherOwner._id);
  const ownerToken = async (person: any, tenant: any) => {
    await RoleAssignment.create({ userId: person._id, gymId: tenant._id, role: "GYM_OWNER", status: "ACTIVE", permissions: OWNER_DEFAULT_PERMISSIONS });
    return (await createSession({ userId: String(person._id), activeRole: "GYM_OWNER", activeGymId: String(tenant._id) })).accessToken;
  };
  const ot = await ownerToken(owner, gym), wrong = await ownerToken(otherOwner, otherGym);
  const ut = (await createSession({ userId: String(user._id), activeRole: "USER" })).accessToken;
  async function api(method: "get" | "post" | "patch", path: string, token: string, body?: object, expected = 200) {
    assertDatabase();
    let operation = request(app)[method]("/api/v1" + path).set("Authorization", `Bearer ${token}`).set("idempotency-key", nanoid()).set("x-csrf-protection", "1");
    if (body) operation = operation.send(body);
    const response = await operation;
    assert.equal(response.status, expected, `${method} ${path}: ${response.body?.error?.code || response.status}`);
    return response.body;
  }
  const plan = await MembershipPlan.create({ publicId: nanoid(), gymId: gym._id, name: "Paid lifecycle plan", code: nanoid(), durationDays: 30, priceMinor: 12000, freezeDaysAllowed: 7, status: "ACTIVE" });
  const today = new Date().toISOString().slice(0, 10);
  const paid = (await api("post", "/owner/members", ot, { name: user.name, email: user.email, planId: plan.publicId, startsAt: today, payment: { amountMinor: 12000, method: "CASH", paidAt: today } }, 201)).data;
  await acceptFixtureInvitation(paid.member._id, String(user._id));
  const originalStart = paid.subscription.startsAt, originalEnd = paid.subscription.endsAt;
  const qr = (await api("get", "/owner/attendance/qr", ot)).data.token;
  await api("post", `/owner/subscriptions/${paid.subscription.publicId}/deactivate`, wrong, { reason: "Wrong tenant" }, 404);
  await api("patch", `/owner/members/${paid.member.publicId}`, ot, { status: "INACTIVE", note: "Temporary access hold" });
  let subscription = await Subscription.findById(paid.subscription._id).lean();
  assert.equal(subscription.status, "DEACTIVATED");
  assert.equal(String(subscription.deactivatedBy), String(owner._id));
  assert(subscription.deactivatedAt);
  await api("post", "/users/me/attendance/check-in", ut, { qrToken: qr }, 403);
  await api("post", `/users/me/subscriptions/${paid.subscription.publicId}/reactivate`, ut, {}, 403);
  await api("patch", `/owner/members/${paid.member.publicId}`, ot, { status: "ACTIVE", note: "Hold resolved" });
  subscription = await Subscription.findById(paid.subscription._id).lean();
  assert.equal(subscription.status, "ACTIVE");
  assert.equal(subscription.startsAt.toISOString(), originalStart);
  assert.equal(subscription.endsAt.toISOString(), originalEnd);
  assert.equal(String(subscription.reactivatedBy), String(owner._id));
  assert.equal((await MemberProfile.findById(paid.member._id)).status, "ACTIVE");
  await api("post", "/users/me/attendance/check-in", ut, { qrToken: qr }, 201);
  const transitions = await SubscriptionEvent.find({ subscriptionId: paid.subscription._id, type: { $in: ["DEACTIVATE", "REACTIVATE"] } }).lean();
  assert.equal(transitions.length, 2);
  assert(transitions.every((event) => String(event.actorId) === String(owner._id) && event.occurredAt && event.payload.reason));
  assert.equal(await Notification.countDocuments({ userId: user._id, title: { $in: ["Gym access deactivated", "Membership reactivated"] } }), 2);
  await api("post", `/owner/subscriptions/${paid.subscription.publicId}/cancel`, ot, { reason: "Reversible paid cancellation" });
  await api("post", `/owner/subscriptions/${paid.subscription.publicId}/reactivate`, ot, { reason: "Restore unused paid time" });
  assert.equal((await Subscription.findById(paid.subscription._id)).endsAt.toISOString(), originalEnd);
  await api("post", `/owner/subscriptions/${paid.subscription.publicId}/deactivate`, ot, { reason: "Refund eligibility test" });
  await Payment.updateOne({ _id: paid.payment._id }, { $set: { status: "REFUNDED" } });
  const refundBlocked = await api("post", `/owner/subscriptions/${paid.subscription.publicId}/reactivate`, ot, { reason: "Must not restore refunded access" }, 409);
  assert.equal(refundBlocked.error.code, "PAYMENT_REQUIRED");
  await Payment.updateOne({ _id: paid.payment._id }, { $set: { status: "CAPTURED" } });
  await Subscription.updateOne({ _id: paid.subscription._id }, { $set: { endsAt: new Date(Date.now() - 1000) } });
  const expired = await api("post", `/owner/subscriptions/${paid.subscription.publicId}/reactivate`, ot, { reason: "Must require a new paid period" }, 409);
  assert.equal(expired.error.code, "RENEWAL_REQUIRED");
  results.push("Paid membership deactivate/reactivate is tenant-scoped, audited and notified; access resumes without extending dates, while refunded/expired entitlements require payment");

  const direct = await MemberProfile.create({ publicId: nanoid(), memberCode: nanoid(), gymId: gym._id, userId: directUser._id, status: "ACTIVE", directAccess: true, approvedAt: new Date(), approvedBy: owner._id });
  await api("patch", `/owner/members/${direct.publicId}`, ot, { status: "INACTIVE", note: "Pause approved access" });
  assert.equal((await MemberProfile.findById(direct._id)).directAccess, false);
  await api("patch", `/owner/members/${direct.publicId}`, ot, { status: "ACTIVE", note: "Restore approved access" });
  assert.equal((await MemberProfile.findById(direct._id)).directAccess, true);
  assert.equal(await Subscription.countDocuments({ memberProfileId: direct._id }), 0);
  const directToken = (await createSession({ userId: String(directUser._id), activeRole: "USER" })).accessToken;
  await api("post", "/users/me/attendance/check-in", directToken, { qrToken: qr }, 201);
  await api("post", "/owner/scanner/scan", ot, { memberIdentifier: direct.memberCode, source: "MANUAL" }, 404);
  results.push("Previously approved direct gym access can be paused and restored without inventing a paid membership");

  const streakUser = await makeUser("Calendar member"), streakToken = (await createSession({ userId: String(streakUser._id), activeRole: "USER" })).accessToken;
  const member = await MemberProfile.create({ publicId: nanoid(), memberCode: nanoid(), gymId: gym._id, userId: streakUser._id, status: "ACTIVE" });
  const event = (date: string, extra: object = {}) => AttendanceEvent.create({ publicId: nanoid(), gymId: gym._id, memberProfileId: member._id, userId: streakUser._id, type: "CHECK_IN", occurredAt: new Date(date), localDate: date.slice(0, 10), source: "IMPORT", createdBy: owner._id, idempotencyKey: nanoid(), ...extra });
  await event("2026-09-01T12:00:00Z");
  const second = await event("2026-09-02T12:00:00Z");
  await event("2026-09-03T12:00:00Z");
  await event("2026-09-03T13:00:00Z");
  await event("2026-09-03T14:00:00Z", { gymId: otherGym._id });
  await event("2026-09-03T16:00:00Z", { type: "CHECK_OUT" });
  await event("2099-09-04T12:00:00Z");
  const asOf = new Date("2026-09-03T23:00:00Z");
  const initial = await globalStreak(String(streakUser._id), "UTC", asOf);
  assert.equal(initial.currentStreak, 3); assert.equal(initial.longestStreak, 3); assert.equal(initial.totalVisits, 3);
  const overview = await api("get", "/users/me/attendance?month=2026-09&page=2&limit=2", streakToken);
  assert.equal(overview.data.events.length, 2); assert.equal(overview.meta.page, 2);
  assert.equal(overview.meta.total, 6);
  assert.equal(overview.data.summary.monthlyAttendance, 3);
  assert.deepEqual(overview.data.summary.attendedDays, ["2026-09-01", "2026-09-02", "2026-09-03"]);
  await event("2026-09-03T20:00:00Z", { type: "CORRECTION", supersedesEventId: second._id, reason: "Invalid imported check-in" });
  const corrected = await globalStreak(String(streakUser._id), "UTC", asOf);
  assert.equal(corrected.currentStreak, 1); assert.equal(corrected.longestStreak, 1); assert.equal(corrected.totalVisits, 2);
  const own = await api("get", "/users/me/attendance?month=2026-09", ut);
  assert(!own.data.events.some((row: any) => row.publicId === second.publicId), "Another member's history must never be exposed");
  const india = await globalStreak(String(streakUser._id), "Asia/Kolkata", new Date("2026-09-04T01:00:00Z"));
  assert.equal(india.currentStreak, 1); assert.equal(india.totalVisits, 2);
  await api("get", "/users/me/attendance?month=2026-13", streakToken, undefined, 422);
  await api("get", "/users/me/attendance?timezone=invalid-zone", streakToken, undefined, 422);
  results.push("Calendar streaks deduplicate real multi-gym check-ins, reject future/corrected days, preserve gaps and timezone boundaries, and paginate private history");
  return results;
}
