const secured={security:[{bearerAuth:[]}],responses:{"200":{description:"Successful operation"},"400":{description:"Validation error"},"401":{description:"Authentication required"},"403":{description:"Insufficient role or permission"},"404":{description:"Resource not found"},"409":{description:"State conflict"}}};
const op=(summary:string,tags:string[],secure=true)=>({summary,tags,...(secure?secured:{responses:secured.responses})});
export const openapi={openapi:"3.1.0",info:{title:"GETFIT4U API",version:"1.0.0",description:"Production REST contract for the GETFIT4U gym management and fitness platform."},servers:[{url:"/api/v1"}],components:{securitySchemes:{bearerAuth:{type:"http",scheme:"bearer",bearerFormat:"JWT"}},schemas:{Success:{type:"object",required:["success","data"],properties:{success:{const:true},message:{type:"string"},data:{},meta:{type:"object"}}},Error:{type:"object",required:["success","message"],properties:{success:{const:false},message:{type:"string"},errors:{type:"array",items:{type:"object"}},requestId:{type:"string"}}}}},paths:{
  "/auth/register":{post:op("Register an account",["Auth"],false)},"/auth/login":{post:op("Password login",["Auth"],false)},"/auth/google":{post:op("Google OAuth login",["Auth"],false)},"/auth/otp/request":{post:op("Request OTP",["Auth"],false)},"/auth/otp/verify":{post:op("Verify OTP and login",["Auth"],false)},"/auth/forgot-password":{post:op("Start recovery",["Auth"],false)},"/auth/recovery/verify":{post:op("Verify recovery OTP",["Auth"],false)},"/auth/reset-password":{post:op("Reset password",["Auth"],false)},"/auth/refresh":{post:op("Rotate refresh token",["Auth"],false)},"/auth/logout":{post:op("Logout current device",["Auth"])},"/auth/logout-all":{post:op("Logout all devices",["Auth"])},"/auth/me":{get:op("Current authenticated context",["Auth"])},
  "/public/gyms":{get:op("Search active paid gyms",["Discovery"],false)},"/public/gyms/{slug}":{get:op("Public gym details",["Discovery"],false)},
  "/users/me":{get:op("Get profile",["Member"]),patch:op("Update profile",["Member"])},"/users/me/subscriptions":{get:op("List subscriptions",["Member"])},"/users/me/subscriptions/{id}/{command}":{post:op("Renew, change, freeze or cancel subscription",["Member"])},"/users/me/attendance":{get:op("Attendance history and streaks",["Attendance"])},"/users/me/attendance/qr":{post:op("Issue signed short-lived attendance QR",["Attendance"])},"/users/classes":{get:op("List classes",["Classes"])},"/users/classes/{id}/bookings":{post:op("Book class capacity atomically",["Classes"])},"/users/me/favorites":{get:op("List favorite gyms",["Member"])},"/users/me/reviews":{post:op("Create or update gym review",["Reviews"])},
  "/checkout/platform/quotes":{post:op("Quote an admin-configured registration plan",["Payments"])},"/checkout/platform/orders":{post:op("Start or retry registration checkout",["Payments"])},"/checkout/payments/{id}/cancel":{post:op("Record checkout dismissal without revoking verified capture",["Payments"])},"/checkout/quotes":{post:op("Create immutable plan quote",["Payments"])},"/checkout/orders":{post:op("Create Razorpay order",["Payments"])},"/checkout/verify":{post:op("Verify checkout signature and gateway capture",["Payments"])},"/checkout/payments/{id}":{get:op("Get payment status",["Payments"])},"/webhooks/razorpay":{post:op("Razorpay signed webhook",["Payments"],false)},
  "/owner/dashboard":{get:op("Owner KPIs",["Owner"])},"/owner/gym":{get:op("Get gym profile",["Owner"]),patch:op("Update gym profile",["Owner"])},"/owner/members":{get:op("Paginated members",["Owner"]),post:op("Create member",["Owner"])},"/owner/plans":{get:op("List membership plans",["Owner"]),post:op("Create membership plan",["Owner"])},"/owner/subscriptions":{get:op("Paginated gym subscriptions",["Owner"])},"/owner/scanner/check-in":{post:op("Validate QR and record attendance",["Attendance"])},"/owner/classes":{get:op("List gym classes",["Owner"]),post:op("Create class",["Owner"])},"/owner/trainers":{get:op("List trainers",["Owner"]),post:op("Create trainer",["Owner"])},"/owner/campaigns":{get:op("List campaigns",["Campaigns"]),post:op("Create campaign",["Campaigns"])},"/owner/offers":{get:op("List offers",["Growth"]),post:op("Create offer",["Growth"])},"/owner/ads":{get:op("List advertisements",["Growth"]),post:op("Create advertisement",["Growth"])},"/owner/revenue":{get:op("Revenue, refunds and settlements",["Finance"])},
  "/trainer/dashboard":{get:op("Trainer KPIs",["Trainer"])},"/trainer/clients":{get:op("Assigned clients",["Trainer"])},"/trainer/sessions":{get:op("Trainer sessions",["Trainer"])},"/trainer/workout-plans":{get:op("List workout plans",["Trainer"]),post:op("Create workout plan",["Trainer"])},"/trainer/clients/{memberId}/workout-assignments":{post:op("Assign workout plan",["Trainer"])},"/trainer/clients/{memberId}/progress":{get:op("Get client progress",["Trainer"]),post:op("Record client progress",["Trainer"])},
  "/conversations":{get:op("List authorized conversations",["Messaging"]),post:op("Create conversation",["Messaging"])},"/conversations/{id}/messages":{get:op("Cursor-paginated messages",["Messaging"]),post:op("Send idempotent client message",["Messaging"])},"/conversations/{id}/read":{post:op("Mark conversation read",["Messaging"])},"/devices":{post:op("Register push device",["Notifications"]),delete:op("Revoke push device",["Notifications"])},"/uploads":{post:op("Initiate presigned upload",["Files"])},"/uploads/{id}/complete":{post:op("Verify and complete upload",["Files"])},
  "/locations/config":{get:op("LocationIQ configuration status",["Maps"],false)},"/locations/tiles/{z}/{x}/{y}":{get:op("LocationIQ raster map tile",["Maps"],false)},"/locations/autocomplete":{get:op("LocationIQ address autocomplete",["Maps"],false)},"/locations/geocode":{post:op("Geocode address",["Maps"],false)},"/locations/reverse-geocode":{post:op("Reverse geocode coordinates",["Maps"],false)},"/locations/directions":{post:op("Calculate route and ETA",["Maps"],false)},
  "/admin/dashboard":{get:op("Platform KPIs",["Admin"])},"/admin/registrations":{get:op("Gym registration payment status",["Admin"])},"/admin/gyms":{get:op("Paginated gyms",["Admin"])},"/admin/payments/{id}/refunds":{post:op("Create provider refund",["Admin"])},"/admin/audit-logs":{get:op("Audit history",["Admin"])},"/admin/monitoring/health":{get:op("System health",["Admin"])}
}} as const;
